package com.example.sweep.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFB3C5FF)
val md_theme_dark_onPrimary = Color(0xFF002A76)
val md_theme_dark_primaryContainer = Color(0xFF003FA5)
val md_theme_dark_onPrimaryContainer = Color(0xFFDBE1FF)
val md_theme_dark_secondary = Color(0xFFB3C5FF)
val md_theme_dark_onSecondary = Color(0xFF002A76)
val md_theme_dark_secondaryContainer = Color(0xFF214290)
val md_theme_dark_onSecondaryContainer = Color(0xFFDBE1FF)
val md_theme_dark_tertiary = Color(0xFF83CFFF)
val md_theme_dark_onTertiary = Color(0xFF00344B)
val md_theme_dark_tertiaryContainer = Color(0xFF004C6B)
val md_theme_dark_onTertiaryContainer = Color(0xFFC6E7FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE4E2E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE4E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF45464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C6D0)
val md_theme_dark_outline = Color(0xFF8F909A)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE4E2E6)
val md_theme_dark_inversePrimary = Color(0xFF0054D8)
val md_theme_dark_surfaceTint = Color(0xFFB3C5FF)

val md_theme_light_primary = Color(0xFF0054D8)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDBE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF00184A)
val md_theme_light_secondary = Color(0xFF3D5BA9)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDBE1FF)
val md_theme_light_onSecondaryContainer = Color(0xFF00184A)
val md_theme_light_tertiary = Color(0xFF00658D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC6E7FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E2D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE2E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF45464F)
val md_theme_light_outline = Color(0xFF757680)
val md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFB3C5FF)
val md_theme_light_surfaceTint = Color(0xFF0054D8)

val blue700 = Color(0xFF1D4ED8)
val blue500 = Color(0xFF3B82F6)
val blue100 = Color(0xFFDBEAFE)
val blue50 = Color(0xFFEFF6FF)

val blue_gray400 = Color(0xFF94A3B8)
val blue_gray900 = Color(0xFF0F172A)

val cool_gray300 = Color(0xFFD1D5DB)
val cool_gray400 = Color(0xFF9CA3AF)

val white900 = Color(0xFFFFFFFF)

val seed = Color(0xFF296DFC)