name: Ktlint

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          path: ~/.gradle/caches
          restore-keys: ${{ runner.os }}-gradle-

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Run Ktlint
        run: ./gradlew ktlintCheck
