name: Ktlint

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Run Ktlint
        run: ./gradlew ktlintCheck || true

      - name: Validate Ktlint
        run: |
          if grep -q '.*Error.*' build/reports/ktlint/ktlintMainCheck.txt; then
            echo "Ktlint detected linting errors."
            exit 1
          fi
